# inherit from the proprietary version
#-include device/lge/star-common/BoardConfigCommon.mk

# Board configuration
#
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_PROVIDES_INIT_RC := true
OMAP_ENHANCEMENT := true

TARGET_GLOBAL_CFLAGS += -D__ARM_NEON__ -D__ARM_ARCH_7A__ -mtune=cortex-a8
TARGET_GLOBAL_CPPFLAGS += -D__ARM_NEON__ -D__ARM_ARCH_7A__ -mtune=cortex-a8

TARGET_BOOTLOADER_BOARD_NAME := ignite

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x80000000
#BOARD_PAGE_SIZE := 0x00000800

BOARD_BOOTIMAGE_PARTITION_SIZE     := 5242880
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 5242880
BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 429916160
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_HAS_NO_MISC_PARTITION := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_PREBUILT_KERNEL := device/lge/ignite/kernel
BOARD_VOLD_MAX_PARTITIONS := 8

TARGET_PROVIDES_LIBAUDIO := false
# MultiMedia defines
BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true

USE_CAMERA_STUB := true
BOARD_USES_TI_CAMERA_HAL := true
CAMERA_YUV_FAST_CONVERT := true
CAMERA_ALGO := true
HARDWARE_OMX := true
FW3A := true
ICAP := true
IMAGE_PROCESSING_PIPELINE := true
USE_OVERLAY_FORMAT_DEFAULT_ONLY := true
ifdef HARDWARE_OMX
OMX_JPEG := true
OMX_VENDOR := ti
OMX_VENDOR_INCLUDES := \
   hardware/ti/omx/system/src/openmax_il/omx_core/inc \
   hardware/ti/omx/image/src/openmax_il/jpeg_enc/inc
OMX_VENDOR_WRAPPER := TI_OMX_Wrapper
BOARD_OPENCORE_LIBRARIES := libOMX_Core
BOARD_OPENCORE_FLAGS := -DHARDWARE_OMX=1
BOARD_CAMERA_LIBRARIES := libcamera
endif

